107 refactor indexenum class
Project-OMOTES/simulator-core pull request #132
Opened 2024-07-04 08:41 UTC by samvanderzwan

This pull request can be reviewed and merged if the other outstanding pull request have been handled. A rebase might then be required to avoid merge conflicts

2024-07-22 10:39 UTC, samvanderzwan commented
Rebased this branch on master, now it can be reviewed

2024-07-24 08:29 UTC, MichielTukker requested changes
I don't see any changes related to an indexenum class?? 

Is the gh changes list   messed up due to merge commits (thus showing changes/commits from other branches?)

Maybe this PR needs to be renamed/updated?

2024-07-24 08:29 UTC, MichielTukker commented on ci/win32/profiling.cmd
what does this have to do with "refactoring indexenum" class??

2024-07-24 08:29 UTC, MichielTukker commented on doc/solver/assets/solver_producer.rst
> +Solver producer class
The name deviates from the names used in code  (Solver.ProductionAsset).  As this is dev-documentation, it's important to keep this in sync!

2024-07-24 08:29 UTC, MichielTukker commented on src/simulator_core/entities/assets/asset_abstract.py
> +
Is this ever used anywhere?? (not used in the current unit tests)

2024-08-01 12:09 UTC, MichielTukker commented
Branch commit history is f**** up due to incomplete (but committed!!) merge/rebase?   I did a manual merge in a separate branch and will create a new PR

2024-08-01 12:09 UTC, closed without merging