41 store simulation data
Project-OMOTES/simulator-core pull request #211
Opened 2024-11-14 10:34 UTC by samvanderzwan

We need to discuss the order of calling write_standard_output and write_output, since this order is now required otherwise the write_output is writing away at wrong position.

2024-11-21 10:04 UTC, samvanderzwan commented
Added writing of outputs to the output dataframe.
Added discharge, velocity, pressure loss, pressure loss per meter, heat loss, head supplied and heat demand.

2025-01-06 14:51 UTC, MichielTukker requested changes

2025-01-06 14:51 UTC, MichielTukker commented on src/omotes_simulator_core/entities/assets/production_cluster.py
> +        """Method to write the asset to the output.
Confusing docstring,  it doesn't match what the method actualy does.  This method doesn't write to "the output" (i.e.  console, logging.whatever).  It updates an internal datastructure with the current timestep values.

2025-01-06 14:51 UTC, MichielTukker commented on src/omotes_simulator_core/solver/network/assets/base_asset.py
> +        """Method to get the internal energy of a connection point.
redundant docstring.... 

Why not something like:  "Returns the the internal energy for a specified connection point for the last computed timestep"

2025-01-06 14:51 UTC, MichielTukker commented on unit_test/entities/test_demand_cluster.py
> +    """Test demand cluster."""
completely redundant docstring

2025-01-06 14:51 UTC, MichielTukker commented on unit_test/entities/test_demand_cluster.py
> +        self.assertEqual(demand_cluster.output, [])
These values should be equal to the DEFAULT_* values.  There's a risk of specifying hardcoded values here.

2025-01-06 14:51 UTC, MichielTukker commented on unit_test/entities/test_demand_cluster.py
> +        """Evaluate the creation of a demand cluster object."""
redundant

2025-01-06 14:51 UTC, MichielTukker commented on unit_test/entities/test_demand_cluster.py
> +        """Evaluate the get_actual_heat_supplied method."""  # noqa: D202
Redundant docstring.   

Also,  I understand the #noqa ,  but this could also be resolved with a `pass `statement  (and prevents numerous  linting-ignores littered throughout the code)

2025-01-06 14:51 UTC, MichielTukker commented on src/omotes_simulator_core/entities/assets/demand_cluster.py
>          # Output list
Pointless comment?

2025-01-06 14:51 UTC, MichielTukker commented on src/omotes_simulator_core/entities/assets/demand_cluster.py
>          """
The docstring is just wrong.   This is not a placeholder method!     It also doesn't write to "output" (I would expect console output,  file output, logging, whatever).   It updates an internal datastructure with the values of the latest computed timestep values.

2025-01-06 14:51 UTC, MichielTukker commented on src/omotes_simulator_core/entities/assets/asset_abstract.py
> +        """Calculates and returns the volume flow rate for the given port.
Good docstring,  but could be more complete:  "Calculates the volumetric flow rate for the specified asset port based on fluid temperature/density and mass flow rate from last computed timestep"

2025-01-06 14:51 UTC, MichielTukker commented on src/omotes_simulator_core/entities/assets/pipe.py
> +            self.outputs[i][-1].update(output_dict_temp)
Why the loop?   This happens in the pipe asset,  where we know 100% sure that this thing only has two ports right?

2025-01-06 14:51 UTC, MichielTukker commented on unit_test/solver/network/assets/test_base_asset.py
> +        """Test the get_internal_energy method."""
redundant docstring.  This tests whether the base_asset.get_internal_energy() method reads the value from the correct place in memory.  This is validated by a manual array index computation on lines 318-321,  which corresponds to the documentation of our memory structures (which we probably don't have yet,  but okay...)

2025-01-06 14:51 UTC, MichielTukker commented on unit_test/entities/test_pipe.py
> +        self.assertEqual(velocity, 12.732395447351628)
Please use [assertAlmostEqual ](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertAlmostEqual)

2025-01-08 07:03 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/asset_abstract.py
> +        return self.solver_asset.get_mass_flow_rate(i) / rho
Because now it is clear what the purpose of this function is and we can test it. If you would put it in the write standard output it would be more difficult to test if the volume flow rate is calculated correctly

2025-01-08 07:04 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/demand_cluster.py
> +    def get_actual_heat_supplied(self) -> float:
Yes but you have the set point and the actual heat supplied, which might be different due to shortage of supply or due to temperature losses.
The later we should account for in future.

2025-01-08 07:06 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/pipe.py
> +        return -self.solver_asset.heat_supplied
This is because we have implemented the energy equation as a supply equation. But from user perspective it is more logical to talk about an heat loss for a pipe, hence the minus sign.

2025-01-08 07:07 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/pipe.py
> +                        PROPERTY_HEAT_LOSS: self.get_heat_loss(),
What do you mean with locally?

2025-01-08 07:17 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/production_cluster.py
> +        """Method to write the asset to the output.
Adjusted

2025-01-08 07:17 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/demand_cluster.py
>          """
Adjusted

2025-01-08 07:19 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/asset_abstract.py
> +        """Calculates and returns the volume flow rate for the given port.
added

2025-01-08 07:22 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/pipe.py
> +            self.outputs[i][-1].update(output_dict_temp)
Velocity is calculated on both ports. Adjusted to remove the if statement

2025-01-08 07:24 UTC, samvanderzwan commented on unit_test/solver/network/assets/test_base_asset.py
> +        """Test the get_internal_energy method."""
Doc  string is needed otherwise you get linting error on github

2025-01-08 07:30 UTC, samvanderzwan commented on unit_test/entities/test_pipe.py
> +        self.assertEqual(velocity, 12.732395447351628)
done

2025-01-08 07:37 UTC, samvanderzwan commented on unit_test/entities/test_demand_cluster.py
> +    """Test demand cluster."""
But needed for linting

2025-01-08 07:37 UTC, samvanderzwan commented on src/omotes_simulator_core/solver/network/assets/base_asset.py
> +        """Method to get the internal energy of a connection point.
Adjusted

2025-01-08 07:41 UTC, samvanderzwan commented on unit_test/entities/test_demand_cluster.py
> +        self.assertEqual(demand_cluster.output, [])
Agree and fixed

2025-01-08 07:41 UTC, samvanderzwan commented on unit_test/entities/test_demand_cluster.py
> +        """Evaluate the creation of a demand cluster object."""
Needed for linting

2025-01-08 07:44 UTC, samvanderzwan commented on unit_test/entities/test_demand_cluster.py
> +        """Evaluate the get_actual_heat_supplied method."""  # noqa: D202
Oke did not know that would work, adjusted

2025-01-08 08:04 UTC, samvanderzwan commented
Fixed all issues also merge conflicts. @samvanderzwan can you check and if ok approve

2025-01-17 12:33 UTC, MichielTukker commented on src/omotes_simulator_core/entities/assets/demand_cluster.py
> +    def get_actual_heat_supplied(self) -> float:
So it's the `heat_supplied`  but the naming of the setpoint is wrong?

2025-02-06 09:18 UTC, MichielTukker requested changes

2025-02-06 09:18 UTC, MichielTukker commented on src/omotes_simulator_core/entities/assets/pipe.py
> +        return -self.solver_asset.heat_supplied
Create new issue for changing the naming conventions in the solver:   heat_supplied --> heat flux.  Include definitions in documentation.   Als change solver.Production_asset  to be solver.Heat_boundary  (or whatever name is better)

2025-02-06 09:18 UTC, MichielTukker commented on src/omotes_simulator_core/entities/assets/demand_cluster.py
> +    def get_actual_heat_supplied(self) -> float:
discussed offline

2025-02-06 09:18 UTC, MichielTukker commented on unit_test/entities/test_demand_cluster.py
> +    """Test demand cluster."""
So describe what the test does  (and doesn't do)

2025-02-06 09:18 UTC, MichielTukker commented on unit_test/solver/network/assets/test_base_asset.py
> +        """Test the get_internal_energy method."""
Same

2025-02-06 09:18 UTC, MichielTukker commented on src/omotes_simulator_core/entities/assets/pipe.py
> +                        PROPERTY_HEAT_LOSS: self.get_heat_loss(),
Discussed offline

2025-02-06 13:54 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/demand_cluster.py
> +    def get_actual_heat_supplied(self) -> float:
adjsuted

2025-02-06 14:01 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/pipe.py
> +                        PROPERTY_HEAT_LOSS: self.get_heat_loss(),
done

2025-02-13 13:56 UTC, MichielTukker approved these changes

2025-02-13 13:56 UTC, merged