180 create intergration tests for overall simulator
Project-OMOTES/simulator-core pull request #215
Opened 2024-11-21 10:06 UTC by Jaimepatt

2024-11-21 15:41 UTC, Jaimepatt commented
This is the first version of the integration tests. It runs the sample esdl as a test simulation. For now it runs two tests. The first one calculates the consumption at the demand asset using the mass flow, cp and delta T and compares it with the demand profile from the esdl. The second test checks whether the return temperature is lower than the primary one. 
This cover two of the results variables: mass flow and temperature. I think a good next step would be to add a test to make sure the pressure values make sense. Perhaps checking the pressure drop along the pipe against the know value.
Ready for review @samvanderzwan @mvmeerkerk.

2024-12-19 13:53 UTC, samvanderzwan reviewed
In general good basis, but we need to discuss what do we want to test here, what is the purpose of this test. Do we want to compare with results from previous release or just test if it runs.

2024-12-19 13:53 UTC, samvanderzwan commented on ci/win32/create_venv.cmd
> +py -3.11 -m pip install virtualenv
Why add this, this doe snot seem to have anything to do with the PR and is it required?

2024-12-19 13:53 UTC, samvanderzwan commented on src/omotes_simulator_core/infrastructure/app.py
> +        stop=datetime.strptime("2019-01-01T09:00:00", "%Y-%m-%dT%H:%M:%S"),
This change is not required right, so then remove it.

2024-12-19 13:53 UTC, samvanderzwan commented on unit_test/integration/test_heat_demand.py
> +        callback = Mock()
Please note which function you are mocking

2024-12-19 13:53 UTC, samvanderzwan commented on unit_test/integration/test_heat_demand.py
> +    def test_heat_power(self) -> None:
I do not get why you want to test this, since it might be that the production is to low so the consumption is capped, and this test will fail.

2025-01-17 12:20 UTC, Jaimepatt commented on ci/win32/create_venv.cmd
> +py -3.11 -m pip install virtualenv
I think I just added it to install the repo in my machine and then forgot to remove it afterwards. I will remove it in the next commit.

2025-01-17 12:24 UTC, Jaimepatt commented on src/omotes_simulator_core/infrastructure/app.py
> +        stop=datetime.strptime("2019-01-01T09:00:00", "%Y-%m-%dT%H:%M:%S"),
You're right, I just changed while testing something and forgot to remove it. It's removed in the latest commit.

2025-01-30 08:26 UTC, samvanderzwan commented on unit_test/integration/test_heat_demand.py
> +    def test_heat_power(self) -> None:
We have discussed this and this is resolved

2025-01-30 08:28 UTC, samvanderzwan requested changes
Please check linting errors and one review comment

2025-01-30 08:28 UTC, samvanderzwan commented on unit_test/integration/test_pressure_physics.py
> +if __name__ == '__main__':
please remove this, this is not required for unit tests

2025-01-31 11:15 UTC, Jaimepatt commented on unit_test/integration/test_pressure_physics.py
> +if __name__ == '__main__':
Updated this in the latest commit.

2025-01-31 11:16 UTC, Jaimepatt commented
Hi @samvanderzwan I just updated this PR based on the meeting we had about two weeks ago. Can you please review? If you don't have any comments, the PR is now finished from my side.

2025-02-03 14:09 UTC, samvanderzwan approved these changes

2025-02-06 08:27 UTC, merged