add time step in the controller abstract that can be used for setting…
Project-OMOTES/simulator-core pull request #223
Opened 2024-12-06 09:28 UTC by octavianor

… timestep in asset

2025-01-08 08:16 UTC, samvanderzwan requested changes
We need to discuss this implementation, 2 main questions:
1. is setting the time step in the controller is this the best way?
2. How to get the time step to the assets, now you are misusing the set points, The time step is not really a set point. But if we want to have non equidistant time step then that would be ok.

2025-01-08 08:16 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/ates_cluster.py
> +        self.rosim_timestep = 1
What is the unit?

2025-01-08 08:16 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/network_controller.py
> +                PROPERTY_TIMESTEP: self.time_step
You are now setting the time step every time step, but I assume we will always be working with an equidistant time step. Therefore it would make more sense to set the time step once for the storage. We will need to discuss how to do this.

2025-01-17 13:40 UTC, octavianor commented on src/omotes_simulator_core/entities/assets/ates_cluster.py
> +        self.rosim_timestep = 1
hour

2025-01-17 13:41 UTC, octavianor commented on src/omotes_simulator_core/entities/network_controller.py
> +                PROPERTY_TIMESTEP: self.time_step
okay then we park this PR at the moment. Indeed we only need to set timestep once

2025-01-30 08:30 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/ates_cluster.py
> +        self.rosim_timestep = 1
Please add it similar to previous line. Please also note that we agreed to use SI in simulator core and here you are deviating from that. We need to discuss or it needs to be in the documentation.

2025-01-30 08:30 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/network_controller.py
> +                PROPERTY_TIMESTEP: self.time_step
oke

2025-02-06 12:12 UTC, vanmeerkerk commented on src/omotes_simulator_core/entities/assets/ates_cluster.py
> +        self.rosim_timestep = 1
Add a description - small docstring - of the property above the init of the class. That might clarify somethings as later on in the code you actually use seconds and only transform the seconds to hours for the rosim model.

2025-02-06 12:13 UTC, vanmeerkerk commented on src/omotes_simulator_core/entities/network_controller.py
> +                PROPERTY_TIMESTEP: self.time_step
Can we not set this property using the set physical properties of the asset? Or is that also called each timestep? @samvanderzwan

2025-03-06 16:28 UTC, closed without merging

2025-03-06 16:29 UTC, octavianor commented
has been replaced by this merge request #262