add ideal heat buffer tracking fill level
Project-OMOTES/simulator-core pull request #225
Opened 2024-12-09 15:45 UTC by octavianor

2025-01-08 08:26 UTC, samvanderzwan requested changes, later dismissed

2025-01-08 08:26 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +        self.maximum_volume = 1  # 1000 L
just but m3 here

2025-01-08 08:26 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +        # Output list
remove redundant comment

2025-01-08 08:26 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +    """A HeatBuffer represents an asset that consumes heat and produces heat."""
please adjust, it stores heats, and thus has the possibility to supply heat or the consume heat for storage

2025-01-08 08:26 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +        self.solver_asset = ProductionAsset(name=self.name, _id=self.asset_id)
Please add comment why as solver asset the ProductionAsset is used, this is ok, but should be explained

2025-01-08 08:26 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +        """Calculate fill level of the storage."""
You also now the maximum volume, so should we not also calculate the volume stored?

2025-01-08 08:26 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +
You only calculate the volume stored, but you should also track the temperature or the energy stored in the buffer, since now you assume that you can always supply at the temperature which is set, but you will supply at the temperature which is in the buffer.

2025-01-08 08:26 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +        """Method to add physical data to the asset.
This needs to be changed, since we do not use this add_physical_data method anymore.

2025-01-17 09:22 UTC, octavianor commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +        self.solver_asset = ProductionAsset(name=self.name, _id=self.asset_id)
i also dont know, in other asset (demand cluster, ates, etc.) we also dont explain. Should we rename ProductionAsset to GeneralAsset because it is being used for all assets

2025-01-17 09:25 UTC, octavianor commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +
currently I implement ideal buffer, only tracking volume without modeling temperature losses. Thus temperature of storage always at setpoint supply and return

2025-01-17 09:25 UTC, octavianor commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +        """Calculate fill level of the storage."""
indeed we can have both output

2025-01-17 09:36 UTC, octavianor commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +        """Method to add physical data to the asset.
but i still see in asset_abstract in main

2025-01-30 08:43 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +        """Method to add physical data to the asset.
You are correct, I will make issue to remove this.

2025-01-30 08:47 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +
But still without temperature loss, you can have different temperatures as inflow and then you just want to calculate mixing temp of fluid in buffer.

2025-01-30 09:54 UTC, samvanderzwan commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +        self.solver_asset = ProductionAsset(name=self.name, _id=self.asset_id)
It is used for production and consumption since the only difference between them is a minus sign. Basically you could note that from solver perspective the storage acts either as a producer or consumer, based on the setpoint given by the controller.

2025-02-05 12:02 UTC, octavianor commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +        # Output list
done

2025-02-05 12:02 UTC, octavianor commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +        self.solver_asset = ProductionAsset(name=self.name, _id=self.asset_id)
done

2025-02-06 12:02 UTC, vanmeerkerk submitted a review, later dismissed
Hey Ryvo I tried to understand the component but could not yet figure it out. Could you write a manual page describing the equations that you would like to solve?

2025-02-06 12:02 UTC, vanmeerkerk commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +            PROPERTY_TEMPERATURE_RETURN,
The controller is not able to set these values at least not with my understanding of the current implementation. I do not see how it can continously change the hot and cold storage temperatues. You should get some sort of value for the energy it is supplying to the vessel and calculate the new fluid level associated with the mixed hot/cold temperature level, right?

2025-02-07 08:19 UTC, octavianor commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +
[Ideal Buffer model CHESS.pptx](https://github.com/user-attachments/files/18703469/Ideal.Buffer.model.CHESS.pptx)

2025-02-07 08:20 UTC, octavianor commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +
[Buffertank model.docx](https://github.com/user-attachments/files/18703483/Buffertank.model.docx)

2025-02-07 08:23 UTC, octavianor commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +
we conclude that for simplicity , the ideal buffer is tracking energy with a fixed deltaT. Since Energy = Power * dt and Power = deltaT * Flow * HeatCapacity.  Thus it is similar with tracking volume V = V + Flow * dt

2025-02-07 08:28 UTC, octavianor commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +
@samvanderzwan @vanmeerkerk but you are correct, now the implementation is driven by temperature supplied by controller, it should be using temperature from the object itself defined from ESDL carrier.

let's discuss first if this model is enough for our simulator our we want to have more detailed model

2025-02-07 08:32 UTC, octavianor commented on src/omotes_simulator_core/adapter/transforms/esdl_asset_mappers/heat_buffer_mapper.py
> +class EsdlAssetAtesMapper(EsdlMapperAbstract):
i copy paste from ates, indeed i should change to buffermapper

2025-02-07 08:34 UTC, octavianor commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +            )
I am still implementing this error to make sure the flow that you set from controller does not hit buffer volume constraint. It could be the controller is not taken account this

2025-02-07 08:35 UTC, octavianor commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +        self.timestep = 3600
this is similar with ates discussion, currently it is also fixed there until we have solution to include timestep from controller or esdl

2025-02-07 08:35 UTC, octavianor commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +        self.temperature_supply = DEFAULT_TEMPERATURE
yes indeed, i can rename that also

2025-08-28 12:25 UTC, vanmeerkerk requested changes
Some minor comments should be fine after a final fix

2025-08-28 12:25 UTC, vanmeerkerk commented on src/omotes_simulator_core/entities/assets/controller/controller_storage.py
>              if abs((self.profile["date"][index].to_pydatetime() - time).total_seconds()) < 3600:
This might not work as expected; what is the intention? Maybe we should make an seperate issue to review this part.

2025-08-28 12:25 UTC, vanmeerkerk commented on src/omotes_simulator_core/entities/network_controller.py
>          """
This is still something that needs to be implemented. Revert back the todo.

2025-08-28 12:40 UTC, vanmeerkerk commented on src/omotes_simulator_core/entities/assets/heat_buffer.py
> +    """A HeatBuffer represents an asset that stores heat. Thus, it has the possibility to supply \
The layer mass now remains constant over the calculation; shouldn't that be a parameter defined by the local temperature difference over the layer? So that layer mass is a variable over the height of the storage tank? 

This off course depends on the structure of the tank

2025-08-28 13:30 UTC, vanmeerkerk commented
I checked some more of the implementation, when I create a system with one layer the stored power is approximately 36 MJ after one step (1H), but this increases to 97 MJ for 5 layers, even though the input doesn't change. There might be something wrong with the implementation @octavianor

2025-08-29 09:56 UTC, octavianor commented on ci/win32/typecheck.cmd
> +python -m mypy ./src/omotes_simulator_core ./unit_test/
because the linux script also include unit test, so i just want to make sure it is similar

2026-02-27 07:51 UTC, closed without merging